<?php include_once('home.html') ?>
<?php include_once('app.js') ?>
<?php include_once('dice-1.png') ?>
<?php include_once('dice-2.png') ?>
<?php include_once('dice-3.png') ?>
<?php include_once('dice-4.png') ?>
<?php include_once('dice-5.png') ?>
<?php include_once('dice-6.png') ?>
<?php include_once('mountain.jpg') ?>